/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tp1Parcial.schema;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-09-18")
public class FactsEdge implements org.apache.thrift.TBase<FactsEdge, FactsEdge._Fields>, java.io.Serializable, Cloneable, Comparable<FactsEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FactsEdge");

  private static final org.apache.thrift.protocol.TField INTERNET_USE_FIELD_DESC = new org.apache.thrift.protocol.TField("internetUse", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField INDIVIDUAL_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("individualType", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField GEOGRAPHY_FIELD_DESC = new org.apache.thrift.protocol.TField("geography", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField YEAR_FIELD_DESC = new org.apache.thrift.protocol.TField("year", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField UNITS_FIELD_DESC = new org.apache.thrift.protocol.TField("units", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FactsEdgeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FactsEdgeTupleSchemeFactory();

  private InternetUseId internetUse; // required
  private IndividualTypeId individualType; // required
  private GeographyId geography; // required
  private java.lang.String year; // required
  private int units; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INTERNET_USE((short)1, "internetUse"),
    INDIVIDUAL_TYPE((short)2, "individualType"),
    GEOGRAPHY((short)3, "geography"),
    YEAR((short)4, "year"),
    UNITS((short)5, "units");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INTERNET_USE
          return INTERNET_USE;
        case 2: // INDIVIDUAL_TYPE
          return INDIVIDUAL_TYPE;
        case 3: // GEOGRAPHY
          return GEOGRAPHY;
        case 4: // YEAR
          return YEAR;
        case 5: // UNITS
          return UNITS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UNITS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INTERNET_USE, new org.apache.thrift.meta_data.FieldMetaData("internetUse", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InternetUseId.class)));
    tmpMap.put(_Fields.INDIVIDUAL_TYPE, new org.apache.thrift.meta_data.FieldMetaData("individualType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, IndividualTypeId.class)));
    tmpMap.put(_Fields.GEOGRAPHY, new org.apache.thrift.meta_data.FieldMetaData("geography", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, GeographyId.class)));
    tmpMap.put(_Fields.YEAR, new org.apache.thrift.meta_data.FieldMetaData("year", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UNITS, new org.apache.thrift.meta_data.FieldMetaData("units", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FactsEdge.class, metaDataMap);
  }

  public FactsEdge() {
  }

  public FactsEdge(
    InternetUseId internetUse,
    IndividualTypeId individualType,
    GeographyId geography,
    java.lang.String year,
    int units)
  {
    this();
    this.internetUse = internetUse;
    this.individualType = individualType;
    this.geography = geography;
    this.year = year;
    this.units = units;
    set_units_isSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FactsEdge(FactsEdge other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.is_set_internetUse()) {
      this.internetUse = new InternetUseId(other.internetUse);
    }
    if (other.is_set_individualType()) {
      this.individualType = new IndividualTypeId(other.individualType);
    }
    if (other.is_set_geography()) {
      this.geography = new GeographyId(other.geography);
    }
    if (other.is_set_year()) {
      this.year = other.year;
    }
    this.units = other.units;
  }

  public FactsEdge deepCopy() {
    return new FactsEdge(this);
  }

  @Override
  public void clear() {
    this.internetUse = null;
    this.individualType = null;
    this.geography = null;
    this.year = null;
    set_units_isSet(false);
    this.units = 0;
  }

  public InternetUseId get_internetUse() {
    return this.internetUse;
  }

  public void set_internetUse(InternetUseId internetUse) {
    this.internetUse = internetUse;
  }

  public void unset_internetUse() {
    this.internetUse = null;
  }

  /** Returns true if field internetUse is set (has been assigned a value) and false otherwise */
  public boolean is_set_internetUse() {
    return this.internetUse != null;
  }

  public void set_internetUse_isSet(boolean value) {
    if (!value) {
      this.internetUse = null;
    }
  }

  public IndividualTypeId get_individualType() {
    return this.individualType;
  }

  public void set_individualType(IndividualTypeId individualType) {
    this.individualType = individualType;
  }

  public void unset_individualType() {
    this.individualType = null;
  }

  /** Returns true if field individualType is set (has been assigned a value) and false otherwise */
  public boolean is_set_individualType() {
    return this.individualType != null;
  }

  public void set_individualType_isSet(boolean value) {
    if (!value) {
      this.individualType = null;
    }
  }

  public GeographyId get_geography() {
    return this.geography;
  }

  public void set_geography(GeographyId geography) {
    this.geography = geography;
  }

  public void unset_geography() {
    this.geography = null;
  }

  /** Returns true if field geography is set (has been assigned a value) and false otherwise */
  public boolean is_set_geography() {
    return this.geography != null;
  }

  public void set_geography_isSet(boolean value) {
    if (!value) {
      this.geography = null;
    }
  }

  public java.lang.String get_year() {
    return this.year;
  }

  public void set_year(java.lang.String year) {
    this.year = year;
  }

  public void unset_year() {
    this.year = null;
  }

  /** Returns true if field year is set (has been assigned a value) and false otherwise */
  public boolean is_set_year() {
    return this.year != null;
  }

  public void set_year_isSet(boolean value) {
    if (!value) {
      this.year = null;
    }
  }

  public int get_units() {
    return this.units;
  }

  public void set_units(int units) {
    this.units = units;
    set_units_isSet(true);
  }

  public void unset_units() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UNITS_ISSET_ID);
  }

  /** Returns true if field units is set (has been assigned a value) and false otherwise */
  public boolean is_set_units() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UNITS_ISSET_ID);
  }

  public void set_units_isSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UNITS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case INTERNET_USE:
      if (value == null) {
        unset_internetUse();
      } else {
        set_internetUse((InternetUseId)value);
      }
      break;

    case INDIVIDUAL_TYPE:
      if (value == null) {
        unset_individualType();
      } else {
        set_individualType((IndividualTypeId)value);
      }
      break;

    case GEOGRAPHY:
      if (value == null) {
        unset_geography();
      } else {
        set_geography((GeographyId)value);
      }
      break;

    case YEAR:
      if (value == null) {
        unset_year();
      } else {
        set_year((java.lang.String)value);
      }
      break;

    case UNITS:
      if (value == null) {
        unset_units();
      } else {
        set_units((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INTERNET_USE:
      return get_internetUse();

    case INDIVIDUAL_TYPE:
      return get_individualType();

    case GEOGRAPHY:
      return get_geography();

    case YEAR:
      return get_year();

    case UNITS:
      return get_units();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INTERNET_USE:
      return is_set_internetUse();
    case INDIVIDUAL_TYPE:
      return is_set_individualType();
    case GEOGRAPHY:
      return is_set_geography();
    case YEAR:
      return is_set_year();
    case UNITS:
      return is_set_units();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof FactsEdge)
      return this.equals((FactsEdge)that);
    return false;
  }

  public boolean equals(FactsEdge that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_internetUse = true && this.is_set_internetUse();
    boolean that_present_internetUse = true && that.is_set_internetUse();
    if (this_present_internetUse || that_present_internetUse) {
      if (!(this_present_internetUse && that_present_internetUse))
        return false;
      if (!this.internetUse.equals(that.internetUse))
        return false;
    }

    boolean this_present_individualType = true && this.is_set_individualType();
    boolean that_present_individualType = true && that.is_set_individualType();
    if (this_present_individualType || that_present_individualType) {
      if (!(this_present_individualType && that_present_individualType))
        return false;
      if (!this.individualType.equals(that.individualType))
        return false;
    }

    boolean this_present_geography = true && this.is_set_geography();
    boolean that_present_geography = true && that.is_set_geography();
    if (this_present_geography || that_present_geography) {
      if (!(this_present_geography && that_present_geography))
        return false;
      if (!this.geography.equals(that.geography))
        return false;
    }

    boolean this_present_year = true && this.is_set_year();
    boolean that_present_year = true && that.is_set_year();
    if (this_present_year || that_present_year) {
      if (!(this_present_year && that_present_year))
        return false;
      if (!this.year.equals(that.year))
        return false;
    }

    boolean this_present_units = true;
    boolean that_present_units = true;
    if (this_present_units || that_present_units) {
      if (!(this_present_units && that_present_units))
        return false;
      if (this.units != that.units)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((is_set_internetUse()) ? 131071 : 524287);
    if (is_set_internetUse())
      hashCode = hashCode * 8191 + internetUse.hashCode();

    hashCode = hashCode * 8191 + ((is_set_individualType()) ? 131071 : 524287);
    if (is_set_individualType())
      hashCode = hashCode * 8191 + individualType.hashCode();

    hashCode = hashCode * 8191 + ((is_set_geography()) ? 131071 : 524287);
    if (is_set_geography())
      hashCode = hashCode * 8191 + geography.hashCode();

    hashCode = hashCode * 8191 + ((is_set_year()) ? 131071 : 524287);
    if (is_set_year())
      hashCode = hashCode * 8191 + year.hashCode();

    hashCode = hashCode * 8191 + units;

    return hashCode;
  }

  @Override
  public int compareTo(FactsEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(is_set_internetUse()).compareTo(other.is_set_internetUse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_internetUse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.internetUse, other.internetUse);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_individualType()).compareTo(other.is_set_individualType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_individualType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.individualType, other.individualType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_geography()).compareTo(other.is_set_geography());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_geography()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.geography, other.geography);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_year()).compareTo(other.is_set_year());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_year()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.year, other.year);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(is_set_units()).compareTo(other.is_set_units());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_units()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.units, other.units);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FactsEdge(");
    boolean first = true;

    sb.append("internetUse:");
    if (this.internetUse == null) {
      sb.append("null");
    } else {
      sb.append(this.internetUse);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("individualType:");
    if (this.individualType == null) {
      sb.append("null");
    } else {
      sb.append(this.individualType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("geography:");
    if (this.geography == null) {
      sb.append("null");
    } else {
      sb.append(this.geography);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("year:");
    if (this.year == null) {
      sb.append("null");
    } else {
      sb.append(this.year);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("units:");
    sb.append(this.units);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!is_set_internetUse()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'internetUse' is unset! Struct:" + toString());
    }

    if (!is_set_individualType()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'individualType' is unset! Struct:" + toString());
    }

    if (!is_set_geography()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'geography' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FactsEdgeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FactsEdgeStandardScheme getScheme() {
      return new FactsEdgeStandardScheme();
    }
  }

  private static class FactsEdgeStandardScheme extends org.apache.thrift.scheme.StandardScheme<FactsEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FactsEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INTERNET_USE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.internetUse = new InternetUseId();
              struct.internetUse.read(iprot);
              struct.set_internetUse_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INDIVIDUAL_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.individualType = new IndividualTypeId();
              struct.individualType.read(iprot);
              struct.set_individualType_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // GEOGRAPHY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.geography = new GeographyId();
              struct.geography.read(iprot);
              struct.set_geography_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // YEAR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.year = iprot.readString();
              struct.set_year_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // UNITS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.units = iprot.readI32();
              struct.set_units_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FactsEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.internetUse != null) {
        oprot.writeFieldBegin(INTERNET_USE_FIELD_DESC);
        struct.internetUse.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.individualType != null) {
        oprot.writeFieldBegin(INDIVIDUAL_TYPE_FIELD_DESC);
        struct.individualType.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.geography != null) {
        oprot.writeFieldBegin(GEOGRAPHY_FIELD_DESC);
        struct.geography.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.year != null) {
        oprot.writeFieldBegin(YEAR_FIELD_DESC);
        oprot.writeString(struct.year);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(UNITS_FIELD_DESC);
      oprot.writeI32(struct.units);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FactsEdgeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FactsEdgeTupleScheme getScheme() {
      return new FactsEdgeTupleScheme();
    }
  }

  private static class FactsEdgeTupleScheme extends org.apache.thrift.scheme.TupleScheme<FactsEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FactsEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.internetUse.write(oprot);
      struct.individualType.write(oprot);
      struct.geography.write(oprot);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.is_set_year()) {
        optionals.set(0);
      }
      if (struct.is_set_units()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.is_set_year()) {
        oprot.writeString(struct.year);
      }
      if (struct.is_set_units()) {
        oprot.writeI32(struct.units);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FactsEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.internetUse = new InternetUseId();
      struct.internetUse.read(iprot);
      struct.set_internetUse_isSet(true);
      struct.individualType = new IndividualTypeId();
      struct.individualType.read(iprot);
      struct.set_individualType_isSet(true);
      struct.geography = new GeographyId();
      struct.geography.read(iprot);
      struct.set_geography_isSet(true);
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.year = iprot.readString();
        struct.set_year_isSet(true);
      }
      if (incoming.get(1)) {
        struct.units = iprot.readI32();
        struct.set_units_isSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

